// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapaDatos.Models
{
    public partial class Color
    {
        public Color()
        {
            OrdenProduccion = new HashSet<OrdenProduccion>();
        }

        public int IdColor { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<OrdenProduccion> OrdenProduccion { get; set; }
    }
}