// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapaDatos.Models
{
    public partial class Defecto
    {
        public Defecto()
        {
            RegistroDefecto = new HashSet<RegistroDefecto>();
        }

        public int IdDefecto { get; set; }
        public int IdTipoDefecto { get; set; }
        public string Descripcion { get; set; }

        public virtual TipoDefecto IdTipoDefectoNavigation { get; set; }
        public virtual ICollection<RegistroDefecto> RegistroDefecto { get; set; }
    }
}