// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapaDatos.Models
{
    public partial class Empleado
    {
        public Empleado()
        {
            Administrador = new HashSet<Administrador>();
            SupervisorCalidad = new HashSet<SupervisorCalidad>();
            SupervisorLinea = new HashSet<SupervisorLinea>();
        }

        public int IdEmpleado { get; set; }
        public string Dni { get; set; }
        public string Descripcion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Rol { get; set; }

        public virtual ICollection<Administrador> Administrador { get; set; }
        public virtual ICollection<SupervisorCalidad> SupervisorCalidad { get; set; }
        public virtual ICollection<SupervisorLinea> SupervisorLinea { get; set; }
    }
}