// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapaDatos.Models
{
    public partial class JornadaLaboral
    {
        public JornadaLaboral()
        {
            Primera = new HashSet<Primera>();
            RegistroDefecto = new HashSet<RegistroDefecto>();
        }

        public int IdJornadaLaboral { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public int? TotalPrimera { get; set; }
        public int? TotalSegunda { get; set; }
        public int IdOrdenProduccion { get; set; }
        public int? IdSupervisorCalidad { get; set; }
        public int IdTurno { get; set; }

        public virtual OrdenProduccion IdOrdenProduccionNavigation { get; set; }
        public virtual SupervisorCalidad IdSupervisorCalidadNavigation { get; set; }
        public virtual Turno IdTurnoNavigation { get; set; }
        public virtual ICollection<Primera> Primera { get; set; }
        public virtual ICollection<RegistroDefecto> RegistroDefecto { get; set; }
    }
}