// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapaDatos.Models
{
    public partial class Linea
    {
        public Linea()
        {
            OrdenProduccion = new HashSet<OrdenProduccion>();
        }

        public int IdLinea { get; set; }
        public bool? Estado { get; set; }
        public string Numero { get; set; }

        public virtual ICollection<OrdenProduccion> OrdenProduccion { get; set; }
    }
}