// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapaDatos.Models
{
    public partial class OrdenProduccion
    {
        public OrdenProduccion()
        {
            JornadaLaboral = new HashSet<JornadaLaboral>();
        }

        public int IdOrdenProduccion { get; set; }
        public int IdLinea { get; set; }
        public int IdSupervisorLinea { get; set; }
        public int IdModelo { get; set; }
        public int IdColor { get; set; }
        public int IdTipoEstado { get; set; }
        public string Numero { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }

        public virtual Color IdColorNavigation { get; set; }
        public virtual Linea IdLineaNavigation { get; set; }
        public virtual Modelo IdModeloNavigation { get; set; }
        public virtual SupervisorLinea IdSupervisorLineaNavigation { get; set; }
        public virtual ICollection<JornadaLaboral> JornadaLaboral { get; set; }
    }
}