// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapaDatos.Models
{
    public partial class Primera
    {
        public int IdPrimera { get; set; }
        public int IdJornadaLaboral { get; set; }
        public DateTime Hora { get; set; }
        public int Cantidad { get; set; }

        public virtual JornadaLaboral IdJornadaLaboralNavigation { get; set; }
    }
}