// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapaDatos.Models
{
    public partial class SupervisorCalidad
    {
        public SupervisorCalidad()
        {
            JornadaLaboral = new HashSet<JornadaLaboral>();
        }

        public int IdSupervisorCalidad { get; set; }
        public int IdEmpleado { get; set; }
        public bool Activo { get; set; }

        public virtual Empleado IdEmpleadoNavigation { get; set; }
        public virtual ICollection<JornadaLaboral> JornadaLaboral { get; set; }
    }
}