// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapaDatos.Models
{
    public partial class SupervisorLinea
    {
        public SupervisorLinea()
        {
            OrdenProduccion = new HashSet<OrdenProduccion>();
        }

        public int IdSupervisorLinea { get; set; }
        public int IdEmpleado { get; set; }
        public bool? Activo { get; set; }

        public virtual Empleado IdEmpleadoNavigation { get; set; }
        public virtual ICollection<OrdenProduccion> OrdenProduccion { get; set; }
    }
}