// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapaDatos.Models
{
    public partial class TipoDefecto
    {
        public TipoDefecto()
        {
            Defecto = new HashSet<Defecto>();
        }

        public int IdTipoDefecto { get; set; }
        public string Tipo { get; set; }

        public virtual ICollection<Defecto> Defecto { get; set; }
    }
}