// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapaDatos.Models
{
    public partial class Turno
    {
        public Turno()
        {
            JornadaLaboral = new HashSet<JornadaLaboral>();
        }

        public int IdTurno { get; set; }
        public TimeSpan HoraInicio { get; set; }
        public TimeSpan HoraFin { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<JornadaLaboral> JornadaLaboral { get; set; }
    }
}